services:
  - type: web
    name: accsmarket-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false

